--ALTER DATABASE MedicalStudio SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
--DROP DATABASE MedicalStudio

-- Crea la base de datos

DROP DATABASE MedicalStudio;
GO

ALTER DATABASE MedicalStudio
SET MULTI_USER;
GO

CREATE DATABASE MedicalStudio;
GO

USE MedicalStudio;
GO

-- Tabla Provincias
CREATE TABLE PROVINCIAS (
    ID_PROVINCIA_PRO INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_PRO VARCHAR(30)
);
GO
INSERT PROVINCIAS(NOMBRE_PRO)
SELECT 'Buenos Aires' UNION
SELECT 'Catamarca' UNION
SELECT 'Chaco' UNION
SELECT 'Chubut' UNION
SELECT 'Córdoba' UNION
SELECT 'Corrientes' UNION
SELECT 'Entre Ríos' UNION
SELECT 'Formosa' UNION
SELECT 'Jujuy' UNION
SELECT 'La Pampa' UNION
SELECT 'La Rioja' UNION
SELECT 'Mendoza' UNION
SELECT 'Misiones' UNION
SELECT 'Neuquén' UNION
SELECT 'Río Negro' UNION
SELECT 'Salta' UNION
SELECT 'San Juan' UNION
SELECT 'San Luis' UNION
SELECT 'Santa Cruz' UNION
SELECT 'Santa Fe' UNION
SELECT 'Santiago del Estero' UNION
SELECT 'Tierra del Fuego' UNION
SELECT 'Tucumán'
GO

-- Tabla Localidades
CREATE TABLE LOCALIDADES(
    ID_LOCALIDAD_LOC INT IDENTITY(1,1) PRIMARY KEY,
    FK_ID_PROVINCIA_LOC INT,
    NOMBRE_LOC VARCHAR(40),
    FOREIGN KEY (FK_ID_PROVINCIA_LOC) REFERENCES Provincias(ID_PROVINCIA_PRO)
);
GO

INSERT INTO LOCALIDADES (FK_ID_PROVINCIA_LOC, NOMBRE_LOC)
SELECT 1, 'La Plata' UNION --BUENOS AIRES
SELECT 1, 'Don Torcuato' UNION
SELECT 1, 'Mar del Plata' UNION
SELECT 1, 'Bahía Blanca' UNION
SELECT 1, 'Tandil' UNION
SELECT 1, 'Avellaneda' UNION
SELECT 1, 'Lanús' UNION
SELECT 1, 'Quilmes' UNION
SELECT 2, 'San Fernando del Valle' UNION --CATAMARCA
SELECT 2, 'Belén' UNION
SELECT 2, 'Andalgalá' UNION
SELECT 2, 'Santa María' UNION
SELECT 3, 'Resistencia' UNION --Chaco
SELECT 3, 'Barranqueras' UNION
SELECT 3, 'Saenz Peña' UNION
SELECT 3, 'Villa Ángela' UNION
SELECT 4, 'Rawson' UNION --Chubut
SELECT 4, 'Trelew' UNION
SELECT 4, 'Comodoro Rivadavia' UNION
SELECT 4, 'Puerto Madryn' UNION
SELECT 5, 'Córdoba' UNION --Córdoba
SELECT 5, 'Río Cuarto' UNION
SELECT 5, 'Villa María' UNION
SELECT 5, 'Bell Ville' UNION
SELECT 6, 'Corrientes' UNION --Corrientes
SELECT 6, 'Goya' UNION
SELECT 6, 'Paso de los Libres' UNION
SELECT 6, 'Mercedes' UNION
SELECT 7, 'Paraná' UNION --Entre Ríos
SELECT 7, 'Concordia' UNION
SELECT 7, 'Gualeguaychú' UNION
SELECT 7, 'Colón' UNION
SELECT 8, 'Formosa' UNION --Formosa
SELECT 8, 'Clorinda' UNION
SELECT 8, 'Pirané' UNION
SELECT 9, 'San Salvador de Jujuy' UNION --Jujuy
SELECT 9, 'Palpalá' UNION
SELECT 9, 'Perico' UNION
SELECT 10, 'Santa Rosa' UNION --La Pampa
SELECT 10, 'General Pico' UNION
SELECT 10, 'Realico' UNION
SELECT 11, 'La Rioja' UNION --La Rioja
SELECT 11, 'Chilecito' UNION
SELECT 11, 'Villa Unión' UNION
SELECT 12, 'Mendoza' UNION --Mendoza
SELECT 12, 'San Rafael' UNION
SELECT 12, 'Malargüe' UNION
SELECT 13, 'Posadas' UNION --Misiones
SELECT 13, 'Oberá' UNION
SELECT 13, 'Iguazú' UNION
SELECT 14, 'Neuquén' UNION --Neuquén
SELECT 14, 'San Martín de los Andes' UNION
SELECT 14, 'Cutral Co' UNION
SELECT 15, 'Viedma' UNION --Río Negro
SELECT 15, 'General Roca' UNION
SELECT 15, 'Cipolletti' UNION
SELECT 16, 'Salta' UNION --Salta
SELECT 16, 'Orán' UNION
SELECT 16, 'Tartagal' UNION
SELECT 17, 'San Juan' UNION --San Juan
SELECT 17, 'Rawson' UNION
SELECT 17, 'Ullum' UNION
SELECT 18, 'San Luis' UNION --San Luis
SELECT 18, 'Villa Mercedes' UNION
SELECT 19, 'Río Gallegos' UNION --Santa Cruz
SELECT 19, 'El Calafate' UNION
SELECT 19, 'Pico Truncado' UNION
SELECT 20, 'Santa Fe' UNION --Santa Fe
SELECT 20, 'Rosario' UNION
SELECT 20, 'Rafaela' UNION
SELECT 21, 'Santiago del Estero' UNION --Santiago del Estero
SELECT 21, 'La Banda' UNION
SELECT 21, 'Termas de Río Hondo' UNION
SELECT 22, 'Ushuaia' UNION --Tierra del Fuego
SELECT 22, 'Rio Grande' UNION
SELECT 23, 'San Miguel de Tucumán' UNION --Tucumán
SELECT 23, 'Concepción' UNION
SELECT 23, 'Tafí Viejo'
GO

-- Tabla Tipo de Usuario
CREATE TABLE TIPO_USUARIO(
    ID_TIPO_USUARIO_TDU INT PRIMARY KEY,
    NOMBRE_TDU VARCHAR(50)
);
GO
INSERT TIPO_USUARIO(ID_TIPO_USUARIO_TDU, NOMBRE_TDU)
SELECT 1, 'Administrador' UNION
SELECT 2, 'Medico'
GO

-- Tabla Usuarios
CREATE TABLE USUARIOS(
    ID_USUARIO_USU INT IDENTITY(1,1) PRIMARY KEY,
    FK_ID_TIPO_USUARIO_USU INT,
    FK_DNI_USU CHAR(8) UNIQUE,
    CONTRA_USU VARCHAR(20),
    FECHA_CREACION_USU DATE,
    FOREIGN KEY (FK_ID_TIPO_USUARIO_USU) REFERENCES TIPO_USUARIO(ID_TIPO_USUARIO_TDU),
    UNIQUE (FK_DNI_USU)
);
GO

INSERT INTO USUARIOS (FK_ID_TIPO_USUARIO_USU, FK_DNI_USU, CONTRA_USU, FECHA_CREACION_USU)
SELECT 1, '12345678', 'password123', GETDATE() UNION
SELECT 1, '87654321', 'password123', GETDATE() UNION
SELECT 1, '23456789', 'password123', GETDATE() UNION
SELECT 1, '98765432', 'password123', GETDATE() UNION
SELECT 1, '34567890', 'password123', GETDATE() UNION
SELECT 1, '45678901', 'password123', GETDATE() UNION
SELECT 1, '56789012', 'password123', GETDATE() UNION
SELECT 1, '67890123', 'password123', GETDATE() UNION
SELECT 1, '78901234', 'password123', GETDATE() UNION
SELECT 1, '89012345', 'password123', GETDATE() UNION
SELECT 1, '90123456', 'password123', GETDATE() UNION
SELECT 1, '01234567', 'password123', GETDATE() UNION
SELECT 1, '10293847', 'password123', GETDATE() UNION
SELECT 1, '56473829', 'password123', GETDATE() UNION
SELECT 1, '91827364', 'password123', GETDATE();
GO

-- Tabla Administrador
CREATE TABLE ADMINISTRADOR(
    ID_USUARIO_DES INT IDENTITY(1,1) PRIMARY KEY,
    FK_DNI_DES CHAR(8) UNIQUE,
    NOMBRE_DES VARCHAR(30),
    APELLIDO_DES VARCHAR(30),
    EMAIL_DES VARCHAR(40),
    TELEFONO_DES VARCHAR(20),
    FOREIGN KEY (ID_USUARIO_DES) REFERENCES USUARIOS(ID_USUARIO_USU)
);
GO
INSERT INTO ADMINISTRADOR(FK_DNI_DES, NOMBRE_DES, APELLIDO_DES, EMAIL_DES, TELEFONO_DES)
SELECT '12345678', 'Juan', 'Pérez', 'juan.perez@example.com', '1123456789' UNION
SELECT '87654321', 'Ana', 'González', 'ana.gonzalez@example.com', '1198765432' UNION
SELECT '23456789', 'Luis', 'Martínez', 'luis.martinez@example.com', '1134567890' UNION
SELECT '98765432', 'María', 'Rodríguez', 'maria.rodriguez@example.com', '1176543210' UNION
SELECT '34567890', 'Carlos', 'Gómez', 'carlos.gomez@example.com', '1145678901' UNION
SELECT '45678901', 'Laura', 'López', 'laura.lopez@example.com', '1167890123' UNION
SELECT '56789012', 'Roberto', 'Díaz', 'roberto.diaz@example.com', '1156789012' UNION
SELECT '67890123', 'Marta', 'Fernández', 'marta.fernandez@example.com', '1189012345' UNION
SELECT '78901234', 'Alberto', 'Ramírez', 'alberto.ramirez@example.com', '1134567899' UNION
SELECT '89012345', 'Cecilia', 'Sánchez', 'cecilia.sanchez@example.com', '1190123456' UNION
SELECT '90123456', 'Diego', 'Ruiz', 'diego.ruiz@example.com', '1145678904' UNION
SELECT '01234567', 'Patricia', 'Jiménez', 'patricia.jimenez@example.com', '1178901234' UNION
SELECT '10293847', 'Ricardo', 'Hernández', 'ricardo.hernandez@example.com', '1155678990' UNION
SELECT '56473829', 'Daniela', 'Castro', 'daniela.castro@example.com', '1147890123' UNION
SELECT '91827364', 'Gabriel', 'Ortiz', 'gabriel.ortiz@example.com', '1198765432';
GO


-- Tabla Especialidades
CREATE TABLE ESPECIALIDADES (
    ID_ESPECIALIDAD_ESP INT IDENTITY(1,1) PRIMARY KEY,
    NOMBRE_ESP VARCHAR(50)
);
GO
INSERT Especialidades(NOMBRE_ESP)
SELECT 'Alergología' UNION
SELECT 'Anestesiología' UNION
SELECT 'Cardiología' UNION
SELECT 'Dermatología' UNION
SELECT 'Endocrinología' UNION
SELECT 'Gastroenterología' UNION
SELECT 'Ginecología' UNION
SELECT 'Neurología' UNION
SELECT 'Oncología' UNION
SELECT 'Oftalmología' UNION
SELECT 'Otorrinolaringología' UNION
SELECT 'Pediatría' UNION
SELECT 'Psiquiatría' UNION
SELECT 'Reumatología' UNION
SELECT 'Traumatología' UNION
SELECT 'Medicina Interna' UNION
SELECT 'Medicina General' UNION
SELECT 'Infectología' UNION
SELECT 'Nefrología' UNION
SELECT 'Neumología' UNION
SELECT 'Cirugía General' UNION
SELECT 'Cirugía Plástica' UNION
SELECT 'Cirugía Cardiaca' UNION
SELECT 'Cirugía Pediátrica'
GO

-- Tabla Medicos
CREATE TABLE MEDICOS(
    ID_MEDICO_MED INT IDENTITY(1,1) PRIMARY KEY,
    FK_DNI_MED CHAR(8) UNIQUE,
    FK_ID_LOCALIDAD_MED INT,
	FK_ID_PROVINCIA_MED INT,
    FK_ID_ESPECIALIDAD_MED INT,
    LEGAJO_MED INT,
    NOMBRE_MED VARCHAR(30),
    APELLIDO_MED VARCHAR(30),
    SEXO_MED CHAR(1),
    NACIONALIDAD_MED VARCHAR(30),
    NACIMIENTO_MED DATE,
    DIRECCION_MED VARCHAR(40),
    EMAIL_MED VARCHAR(40),
	TELEFONO_MED varchar(20),
	ESTADO_MED varchar(20),
    FOREIGN KEY (FK_ID_LOCALIDAD_MED) REFERENCES LOCALIDADES(ID_LOCALIDAD_LOC),
    FOREIGN KEY (FK_ID_ESPECIALIDAD_MED) REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD_ESP)
);
GO


-- Tabla Horario de Atencion
CREATE TABLE HORARIO_ATENCION (
    ID_HORARIO_HDA INT IDENTITY(1,1) PRIMARY KEY,
    FK_DNI_MEDICO_HDA CHAR(8),
    DIA_HDA VARCHAR(45),
    HORA_INICIO_HDA TIME,
    HORA_FIN_HDA TIME,
    FOREIGN KEY (FK_DNI_MEDICO_HDA) REFERENCES MEDICOS(FK_DNI_MED)
);
GO

-- Tabla Pacientes
CREATE TABLE PACIENTES (
    ID_PACIENTE_PAS INT IDENTITY(1,1) PRIMARY KEY,
    FK_ID_LOCALIDAD_PAS INT,
    FK_ID_PROVINCIA_PAS INT,
    DNI_PAS CHAR(8) UNIQUE,
    NOMBRE_PAS VARCHAR(30),
    APELLIDO_PAS VARCHAR(30),
    SEXO_PAS CHAR(1),
    NACIONALIDAD_PAS VARCHAR(30),
    NACIMIENTO_PAS DATE,
    DIRECCION_PAS VARCHAR(40),
    EMAIL_PAS VARCHAR(40),
    TELEFONO_PAS VARCHAR(20),
    ESTADO_PAS VARCHAR(20),
    FOREIGN KEY (FK_ID_LOCALIDAD_PAS) REFERENCES LOCALIDADES(ID_LOCALIDAD_LOC),
    FOREIGN KEY (FK_ID_PROVINCIA_PAS) REFERENCES PROVINCIAS(ID_PROVINCIA_PRO)
);
GO

-- Tabla Turnos
CREATE TABLE TURNOS (
    ID_TURNO_TUR INT IDENTITY(1,1) PRIMARY KEY,
    FK_ID_MEDICO_TUR INT,
    FK_ID_PACIENTE_TUR INT,
    FK_ID_ESPECIALIDAD_TUR INT,
    FECHA_TUR DATE,
    HORA_TUR TIME,
    ESTADO_TUR VARCHAR(20),
    OBSERVACION_TUR TEXT,
    FOREIGN KEY (FK_ID_MEDICO_TUR) REFERENCES MEDICOS(ID_MEDICO_MED),
    FOREIGN KEY (FK_ID_PACIENTE_TUR) REFERENCES PACIENTES(ID_PACIENTE_PAS),
    FOREIGN KEY (FK_ID_ESPECIALIDAD_TUR) REFERENCES ESPECIALIDADES(ID_ESPECIALIDAD_ESP),
	UNIQUE (FK_ID_MEDICO_TUR, FK_ID_PACIENTE_TUR, FECHA_TUR, HORA_TUR)
);
GO

--DROP PROCEDURE spBajaLogicaPaciente
--GO

CREATE PROCEDURE spBajaLogicaPaciente
@DNIPACIENTE char(8)
AS
UPDATE PACIENTES SET ESTADO_PAS = 'Inactivo'
WHERE DNI_PAS = @DNIPACIENTE
RETURN
GO

--DROP PROCEDURE spModificarPaciente
--GO

CREATE PROCEDURE spModificarPaciente
@DNIPACIENTE char(8), @LOCALIDAD int, @PROVINCIA int, @NOMBRE varchar(30), @APELLIDO varchar(30), @SEXO char(1), @NACIONALIDAD VARCHAR(30), @NACIMIENTO Date,
@DIRECCION varchar(40), @EMAIL varchar(40), @TELEFONO VARCHAR(20)
AS
UPDATE PACIENTES SET FK_ID_LOCALIDAD_PAS = @LOCALIDAD, FK_ID_PROVINCIA_PAS = @PROVINCIA, NOMBRE_PAS = @NOMBRE, APELLIDO_PAS = @APELLIDO, SEXO_PAS = @SEXO, NACIONALIDAD_PAS = @NACIONALIDAD,
NACIMIENTO_PAS = @NACIMIENTO ,DIRECCION_PAS = @DIRECCION, EMAIL_PAS = @EMAIL, TELEFONO_PAS = @TELEFONO
WHERE DNI_PAS = @DNIPACIENTE
RETURN
GO

--DROP PROCEDURE spBajaLogicaMedico
--GO

CREATE PROCEDURE spBajaLogicaMedico
@DNIMEDICO char(8)
AS
UPDATE MEDICOS SET ESTADO_MED = 'Inactivo'
WHERE FK_DNI_MED = @DNIMEDICO
RETURN
GO

--DROP PROCEDURE spModificarMedico
--GO

CREATE PROCEDURE spModificarMedico
@DNIMEDICO char(8), @LOCALIDAD int, @PROVINCIA int, @ESPECIALIDAD int, @NOMBRE varchar(30), @APELLIDO varchar(30), @SEXO char(1), 
@NACIONALIDAD VARCHAR(30), @NACIMIENTO Date, @DIRECCION varchar(40), @EMAIL varchar(40), @TELEFONO VARCHAR(20), 
@DIAS varchar(45), @HORARIO varchar(13)
AS
UPDATE MEDICOS SET FK_ID_LOCALIDAD_MED = @LOCALIDAD, FK_ID_PROVINCIA_MED = @PROVINCIA, FK_ID_ESPECIALIDAD_MED = @ESPECIALIDAD, NOMBRE_MED = @NOMBRE, 
APELLIDO_MED = @APELLIDO, SEXO_MED = @SEXO, NACIONALIDAD_MED = @NACIONALIDAD, NACIMIENTO_MED = @NACIMIENTO , DIRECCION_MED = @DIRECCION, 
EMAIL_MED = @EMAIL, TELEFONO_MED = @TELEFONO
WHERE FK_DNI_MED = @DNIMEDICO

UPDATE HORARIO_ATENCION SET DIA_HDA = @DIAS, HORA_INICIO_HDA = LEFT(@HORARIO, 5), HORA_FIN_HDA = RIGHT(@HORARIO, 5)
WHERE FK_DNI_MEDICO_HDA = @DNIMEDICO
RETURN
GO